// sistema-penal/src/app/atividades/add-atividade/add-atividade.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AtividadeService } from '../atividade.service';

@Component({
  selector: 'app-add-atividade',
  templateUrl: './add-atividade.component.html',
  styleUrls: ['./add-atividade.component.css']
})
export class AddAtividadeComponent {
  form: FormGroup;
  resposta: string = '';
  respostaClasse: string = '';

  constructor(
    private fb: FormBuilder,
    private atividadeService: AtividadeService
  ) {
    this.form = this.fb.group({
      cpf: ['', [Validators.required, Validators.pattern(/^\d{11}$/)]],
      tipoAtividade: ['', Validators.required],
      prisioneiroId: [''],
      descricao: [''],
      isbn: [''],
      materia: ['']
    });
  }

  async buscarCpf() {
    const cpf = this.form.value.cpf;
    if (!this.form.controls['cpf'].valid) {
      this.resposta = 'Por favor, insira um CPF com 11 dígitos (use apenas números).';
      this.respostaClasse = 'resposta-erro';
      return;
    }
    
    try {
      const prisioneiro = await this.atividadeService.buscarPorCpf(cpf);
      if (!prisioneiro?.id) {
        this.resposta = 'Prisioneiro não encontrado.';
        this.respostaClasse = 'resposta-erro';
        return;
      }
  
      this.form.patchValue({ prisioneiroId: prisioneiro.id });
      this.resposta = 'Prisioneiro encontrado.';
      this.respostaClasse = 'resposta-sucesso';
    } catch (err) {
      this.resposta = 'Erro ao conectar com o servidor.';
      this.respostaClasse = 'resposta-erro';
    }
  }

  async onSubmit() {
    const { tipoAtividade, prisioneiroId, descricao, isbn, materia } = this.form.value;

    let payload: any = { prisioneiroId };

    if (tipoAtividade === 'dias-de-trabalho') {
      payload.descricao = descricao;
    } else if (tipoAtividade === 'estudos') {
      payload.materia = materia;
    } else if (tipoAtividade === 'livros') {
      payload.isbn = isbn;
    }

    try {
      await this.atividadeService.adicionarAtividade(tipoAtividade, payload);
      alert('Atividade adicionada com sucesso!');
    } catch (err) {
      alert('Erro ao adicionar atividade.');
    }
  }
}

<div class="main-content">
    <div id="form">
        <h1>Cadastrar Atividade a Prisioneiro</h1>
        <form [formGroup]="form" (ngSubmit)="onSubmit()">
            <label>
                CPF do prisioneiro (apenas números):
                <input formControlName="cpf" type="text"/>
            </label>
            <button type="button" (click)="buscarCpf()">Buscar Prisioneiro</button>
            <div [ngClass]="respostaClasse">{{ resposta }}</div>

            <label>
                Nome da Atividade:
                <select formControlName="tipoAtividade">
                    <option value="estudos">Estudo</option>
                    <option value="livros">Livro</option>
                    <option value="dias-de-trabalho">Dia de Trabalho</option>
                </select>
            </label>

            <div *ngIf="form.value.tipoAtividade === 'dias-de-trabalho'">
                <label>
                Descrição do Trabalho:
                <input formControlName="descricao" type="text" />
                </label>
            </div>

            <div *ngIf="form.value.tipoAtividade === 'livros'">
                <label>
                ISBN 11 do livro:
                <input formControlName="isbn" type="text" />
                </label>
            </div>

            <div *ngIf="form.value.tipoAtividade === 'estudos'">
                <label>
                Matéria estudada:
                <input formControlName="materia" type="text" />
                </label>
            </div>

            <button type="submit" [disabled]="form.invalid">Cadastrar</button>
        </form>
    </div>
</div>

// sistema-penal/src/components/atividade/AddAtividade.tsx
import { useState } from "react";
import api from "../../api";

type TipoAtividade = "dias-de-trabalho" | "estudos" | "livros";

function AddAtividade() {
  const [prisioneiroId, setPrisioneiroId] = useState<string>("");
  const [tipoAtividade, setTipoAtividade] = useState<TipoAtividade>();
  const [descricao, setDescricao] = useState<string>(""); // ana: pra dia de trabalhoa
  const [isbn, setIsbn] = useState<string>(""); // ana: pra livro
  const [materia, setMateria] = useState<string>(""); // ana: pra estudo
  const [resposta, setResposta] = useState("");
  const [respostaClasse, setRespostaClasse] = useState("");
  const [cpf, setCpf] = useState<string>("");

  const handleBuscarCpf = async () => {
    if (cpf.length !== 11) {
      setResposta("Por favor, insira um CPF com 11 dígitos.");
      setRespostaClasse("resposta-erro");
      return;
    }

    try {
      const res = await api.get(`/prisioneiros/cpf/${cpf}`);
      const prisioneiro = res.data;

      if (!prisioneiro || !prisioneiro.id) {
        setResposta("Prisioneiro não encontrado");
        setRespostaClasse("resposta-erro");
        return;
      }

      setPrisioneiroId(prisioneiro.id);
      setResposta("Prisioneiro encontrado");
      setRespostaClasse("resposta-sucesso");
    } catch (err) {
      setResposta("Erro ao conectar com o servidor.");
      setRespostaClasse("resposta-erro");
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const atividadeBase = {
      prisioneiroId
    };

    // ana: adiciona coisinhas especificas baseado no tipo de atividade
    let payload: any = atividadeBase;

    if (tipoAtividade === "dias-de-trabalho") {
      payload = { ...atividadeBase, descricao };
    }
    else if (tipoAtividade === "estudos") {
      payload = { ...atividadeBase, materia };
    } 
    else if ( tipoAtividade === "livros") {
      payload = { ...atividadeBase, isbn };
    }

    try {
      const res = await api.post(`/${tipoAtividade}`, payload);

      if (res.status === 200) {
        alert("Atividade adicionada com sucesso!");
      } else {
        alert("Impossível adicionar atividade.");
      }
    } catch {
      alert("Erro ao conectar com o servidor.");
    }
  };

  return (
    <div className="main-content">
      <div id="form">
        <h1>Cadastrar Atividade a Prisioneiro</h1>
        <form onSubmit={handleSubmit}>
        <label>
          CPF do Prisioneiro (apenas números):
          <input
            type="text"
            value={cpf}
            onChange={(e) => setCpf(e.target.value)}
            required
          />
        </label>
        <button type="button" onClick={handleBuscarCpf}>
          Buscar Prisioneiro
        </button>
        <div className={respostaClasse}>{resposta}</div>

          {/* ana: aqui as partes específicas! :> */}
          <label>
            Nome da Atividade:
            <select
              value={tipoAtividade}
              onChange={(e) => setTipoAtividade(e.target.value as TipoAtividade)}
              required
            >
              <option value="estudos">Estudo</option>
              <option value="livros">Livro</option>
              <option value="dias-de-trabalho">Dia de Trabalho</option>
            </select>
          </label>

          {tipoAtividade === "dias-de-trabalho" && (
            <label>
              Descrição do Trabalho:
              <input
                type="text"
                value={descricao}
                onChange={(e) => setDescricao(e.target.value)}
              />
            </label>
          )}

          {tipoAtividade === "livros" && (
            <label>
              ISBN 11 do livro:
              <input
                type="text"
                value={isbn}
                onChange={(e) => setIsbn(e.target.value)}
              />
            </label>
          )}

          {tipoAtividade === "estudos" && (
            <label>
              Matéria estudada:
              <input
                type="text"
                value={materia}
                onChange={(e) => setMateria(e.target.value)}
              />
            </label>
          )}

          <button type="submit">Cadastrar</button>
        </form>
      </div>
    </div>
  );
}

export default AddAtividade;
