// sistema-penal/src/app/atividades/listar-atividades/listar-atividades.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { AtividadeService } from '../atividade.service';

type TipoAtividade = 'dias-de-trabalho' | 'estudos' | 'livros';

interface Atividade {
  id: number;
  prisioneiroId: string;
  data: string;
  descricao?: string;
  isbn?: string;
  materia?: string;
}

@Component({
  selector: 'app-listar-atividades',
  templateUrl: './listar-atividades.component.html',
  styleUrls: ['./listar-atividades.component.css']
})
export class ListarAtividadesComponent {
  form: FormGroup;
  atividades: Atividade[] = [];
  erro: string = '';

  constructor(
    private fb: FormBuilder,
    private atividadeService: AtividadeService
  ) {
    this.form = this.fb.group({
      tipoAtividade: ['dias-de-trabalho']
    });
  }

  async buscarAtividades() {
    const tipo: TipoAtividade = this.form.value.tipoAtividade;

    try {
      const atividades = await this.atividadeService.listarAtividades(tipo);
      this.atividades = atividades;
      this.erro = '';
    } catch (err) {
      console.error('Erro ao buscar atividades:', err);
      this.atividades = [];
      this.erro = 'Erro ao encontrar atividades.';
    }
  }

  detalhesAtividade(atividade: Atividade): string {
    if (atividade.descricao) return atividade.descricao;
    if (atividade.isbn) return atividade.isbn;
    if (atividade.materia) return atividade.materia;
    return 'Sem detalhes disponíveis.';
  }
}
<div class="main-content">
  <div id="form">
    <h1>Listar Atividades</h1>
    <form [formGroup]="form" (ngSubmit)="buscarAtividades()">
      <label>
        Nome da Atividade:
        <select formControlName="tipoAtividade">
          <option value="estudos">Estudo</option>
          <option value="livros">Livro</option>
          <option value="dias-de-trabalho">Dia de Trabalho</option>
        </select>
      </label>
      <button type="submit">Buscar Atividades</button>
    </form>

    <p class="erro" *ngIf="erro">{{ erro }}</p>

    <div class="lista-atividades" *ngIf="atividades.length > 0">
      <table>
        <thead>
          <tr>
            <th>ID do Prisioneiro</th>
            <th>Data</th>
            <th>Detalhes</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let atividade of atividades">
            <td>{{ atividade.prisioneiroId }}</td>
            <td>{{ atividade.data | date:'shortDate' }}</td>
            <td>{{ detalhesAtividade(atividade) }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <p *ngIf="atividades.length === 0 && !erro">Nenhuma atividade encontrada.</p>
  </div>
</div>

// sistema-penal/src/components/atividade/ListarAtividades.tsx
import { useState } from "react";
import api from "../../api";

type TipoAtividade = "dias-de-trabalho" | "estudos" | "livros";

type Atividade = {
  id: number;
  prisioneiroId: string;
  data: string;
  descricao?: string;
  isbn?: string;
  materia?: string;
};

function ListarAtividades() {
  const [tipoAtividade, setTipoAtividade] = useState<TipoAtividade>("dias-de-trabalho");
  const [atividades, setAtividades] = useState<Atividade[]>([]);
  const [erro, setErro] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      const res = await api.get(`${tipoAtividade}`);
      console.log("Atividades recebidas:", res.data);

      if (res.status === 200) {
        setAtividades(res.data);
        setErro("");
      } else {
        setErro("Erro ao encontrar atividades.");
        setAtividades([]);
      }
    } catch (err) {
      console.error("Erro ao conectar com o servidor:", err);
      alert("Erro ao conectar com o servidor.");
      setAtividades([]);
    }
  };

  const renderDetalhesAtividade = (atividade: Atividade) => {
    if (atividade.descricao) {
      return <>{atividade.descricao}</>;
    } else if (atividade.isbn) {
      return <>{atividade.isbn}</>;
    } else if (atividade.materia) {
      return <>{atividade.materia}</>;
    } else {
      return <em>Sem detalhes disponíveis.</em>;
    }
  };

  return (
    <div className="main-content">
      <div id="form">
        <h1>Listar Atividades</h1>
        <form onSubmit={handleSubmit}>
          <label>
            Nome da Atividade:
            <select
              value={tipoAtividade}
              onChange={(e) => setTipoAtividade(e.target.value as TipoAtividade)}
              required
            >
              <option value="estudos">Estudo</option>
              <option value="livros">Livro</option>
              <option value="dias-de-trabalho">Dia de Trabalho</option>
            </select>
          </label>
          <button type="submit">Buscar Atividades</button>
        </form>

        {erro && <p className="erro">{erro}</p>}

        <div className="lista-atividades">
          {atividades.length === 0 && !erro && <p>Nenhuma atividade encontrada.</p>}

          <table>
            <thead>
              <tr>
                <th>ID do Prisioneiro</th>
                <th>Data</th>
                <th>Detalhes</th>
              </tr>
            </thead>
            <tbody>
              {atividades.map((atividade) => (
                <tr key={atividade.id}>
                  <td>{atividade.prisioneiroId}</td>
                  <td>{new Date(atividade.data).toLocaleDateString()}</td>
                  <td>{renderDetalhesAtividade(atividade)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

export default ListarAtividades;
