// sistema-penal/src/components/funcionario/Login.tsx
import { useState } from "react";
import axios from "axios";
import { Navigate } from "react-router-dom";

function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [redirect, setRedirect] = useState(false);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    try {
      const res = await axios.post("http://localhost:5034/auth/login", {
        Email: username,
        Senha: password,
      });

      console.log(res.data);
      const token = res.data.token;
      localStorage.setItem("token", token);
      setRedirect(true);
    } catch {
      setError("Usuário ou senha inválidos.");
    }
  };

  return (
    <div className="form-container">
      <h1>Login</h1>
      <form onSubmit={handleLogin} className="form-content">
        <div className="form-group">
          <label htmlFor="username">
            Usuário:
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
            />
          </label>
        </div>
        <div className="form-group">
          <label htmlFor="password">
            Senha:
            <input
              type="text"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </label>
        </div>
        <button className="form-submit-button" type="submit">
          Entrar
        </button>
        {error && <p className="resposta-erro">{error}</p>}
        {redirect && <Navigate to="/listar/funcionario" />}
      </form>
    </div>
  );
}
export default Login;

// sistema-penal/src/app/auth/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
})
export class LoginComponent {
  username = '';
  password = '';
  error = '';

  constructor(private authService: AuthService, private router: Router) {}

  handleLogin() {
    this.error = '';
    this.authService.login(this.username, this.password).subscribe({
      next: () => this.router.navigate(['/listar/funcionario']),
      error: () => this.error = 'Usuário ou senha inválidos.',
    });
  }
}

<div>
  <div>
    <h1>Login</h1>
    <form (ngSubmit)="handleLogin()">
      <div class="form-group">
        <label for="username">Usuário:</label>
        <input type="text" [(ngModel)]="username" name="username" required />
      </div>
      <div class="form-group">
        <label for="password">Senha:</label>
        <input type="password" [(ngModel)]="password" name="password" required />
      </div>
      <button class="form-submit-button" type="submit">Entrar</button>
      <p class="resposta-erro" *ngIf="error">{{ error }}</p>
    </form>
  </div>
</div>
